# This file was automatically generated by Sbtix. Do not edit manually.
{
  "versioning" = [{
      "scalaVersion" = "2.12.5";
      "sbtVersion" = "1.1.4";
    }];
  "repos" = {
    "nix-public" = "";
  };
  "artifacts" = {
    "nix-public/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.jar" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.jar";
      sha256 = "30B792E2745752FAD8E1F92CA750D5F2D480EDD2C5E99BC098AAEBE22EB48C22";
    };
    "nix-public/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.pom" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.pom";
      sha256 = "8FE8C84F238E235336993624FC698DEF0F257EC84F47711564041A9010C8C68E";
    };
    "nix-public/ch/qos/logback/logback-core/1.1.2/logback-core-1.1.2.jar" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.1.2/logback-core-1.1.2.jar";
      sha256 = "90F1DFCA25CD776F28A589F58B181D0E6787668A1B1FA8510BEAD402F86EDCB1";
    };
    "nix-public/ch/qos/logback/logback-core/1.1.2/logback-core-1.1.2.pom" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.1.2/logback-core-1.1.2.pom";
      sha256 = "3CAD40EE01D5D4A5B92C74B6562C8B8ECDAAD254273BFEA97F35F8E18B024EE1";
    };
    "nix-public/ch/qos/logback/logback-parent/1.1.2/" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-parent/1.1.2/";
      sha256 = "22C000CAB1311AD604FB3D165A464960DD5BD26C23FFAAA74A5CDEDD95F80D7B";
    };
    "nix-public/ch/qos/logback/logback-parent/1.1.2/logback-parent-1.1.2.pom" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-parent/1.1.2/logback-parent-1.1.2.pom";
      sha256 = "07EF142CABE0E1FD41002D01CE6A5758F26200731859CC15EB81AA80EBFC4E8C";
    };
    "nix-public/com/rabbitmq/amqp-client/3.5.7/amqp-client-3.5.7.jar" = {
      url = "https://repo1.maven.org/maven2/com/rabbitmq/amqp-client/3.5.7/amqp-client-3.5.7.jar";
      sha256 = "0D8971BE4F3F03D3421E0012E5A6E8C95E9C60A83C566EC5CD9F44580A1D71B6";
    };
    "nix-public/com/rabbitmq/amqp-client/3.5.7/amqp-client-3.5.7.pom" = {
      url = "https://repo1.maven.org/maven2/com/rabbitmq/amqp-client/3.5.7/amqp-client-3.5.7.pom";
      sha256 = "35261ACE681E27A8B25BE2F1DF150B910C692324B1FAD5A7C8A35638DC3549E0";
    };
    "nix-public/com/typesafe/akka/akka-actor_2.12/2.5.11/akka-actor_2.12-2.5.11.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.5.11/akka-actor_2.12-2.5.11.jar";
      sha256 = "EAE01C4E9AF35258AEA9120FAED949C6336A4A76586BCDE7D4C3B439ACFF9AEF";
    };
    "nix-public/com/typesafe/akka/akka-actor_2.12/2.5.11/akka-actor_2.12-2.5.11.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.5.11/akka-actor_2.12-2.5.11.pom";
      sha256 = "0490F08739AC65A7AB5E60EED23478977188AC1975886CAEA8D26A8C4B2B293E";
    };
    "nix-public/com/typesafe/akka/akka-slf4j_2.12/2.5.11/akka-slf4j_2.12-2.5.11.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-slf4j_2.12/2.5.11/akka-slf4j_2.12-2.5.11.jar";
      sha256 = "63CC814076DF578C30F60A1E2D609A2CA9D04057B4223A3244FF66980CDEC122";
    };
    "nix-public/com/typesafe/akka/akka-slf4j_2.12/2.5.11/akka-slf4j_2.12-2.5.11.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-slf4j_2.12/2.5.11/akka-slf4j_2.12-2.5.11.pom";
      sha256 = "9A4F557DDDD493949E27F3A1D27292EF2B4850E7C6A0D42B72F97A7E198F27AF";
    };
    "nix-public/com/typesafe/akka/akka-testkit_2.12/2.5.11/akka-testkit_2.12-2.5.11.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-testkit_2.12/2.5.11/akka-testkit_2.12-2.5.11.jar";
      sha256 = "C59F21D7CA645A992B059D7FE8C6D967EC19F40096C1DC695173E3C4A970B9C8";
    };
    "nix-public/com/typesafe/akka/akka-testkit_2.12/2.5.11/akka-testkit_2.12-2.5.11.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-testkit_2.12/2.5.11/akka-testkit_2.12-2.5.11.pom";
      sha256 = "65830072013E2F8CCBB40ECBB4DB1458BF59AA7DC23F55ACD09F61345B7E0883";
    };
    "nix-public/com/typesafe/config/1.3.2/config-1.3.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.2/config-1.3.2.jar";
      sha256 = "6563D1723F3300BF596F41E40BC03E54986108B5C45D0AC34EBC66D48C2E25A3";
    };
    "nix-public/com/typesafe/config/1.3.2/config-1.3.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.2/config-1.3.2.pom";
      sha256 = "07EE48EC393761693CB95E2D1778CCAF3AD680312E94EB27C0059B8E06C98DBA";
    };
    "nix-public/jline/jline/2.14.5/jline-2.14.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.5/jline-2.14.5-javadoc.jar";
      sha256 = "B7C16280BABD7DF343BF8206CF50223E5E03795FADEFC4BFB659B1CA64D5490F";
    };
    "nix-public/jline/jline/2.14.5/jline-2.14.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.5/jline-2.14.5-sources.jar";
      sha256 = "4A711057AE82BEE8C6D4079692D2DED385B9BA37A1C9BB5210C8CAA4C1A9FFB2";
    };
    "nix-public/jline/jline/2.14.5/jline-2.14.5.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.5/jline-2.14.5.jar";
      sha256 = "4F347BC90D6F5CE61C0F8928D44A7B993275CEAA7D7F237714518A9BDD5003CE";
    };
    "nix-public/jline/jline/2.14.5/jline-2.14.5.pom" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.5/jline-2.14.5.pom";
      sha256 = "FD46EB30C70F882BDA418B0859F63F3D9C49538610ED0B99FB11F32F8B8A64DE";
    };
    "nix-public/junit/junit/4.12/junit-4.12.jar" = {
      url = "https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.jar";
      sha256 = "59721F0805E223D84B90677887D9FF567DC534D7C502CA903C0C2B17F05C116A";
    };
    "nix-public/junit/junit/4.12/junit-4.12.pom" = {
      url = "https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.pom";
      sha256 = "90F163F78E3FFB6F1C7AD97DE9E7EBA4EEA25807141B85D6D12BE67CA25449C4";
    };
    "nix-public/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar";
      sha256 = "66FDEF91E9739348DF7A096AA384A5685F4E875584CCE89386A7A47251C4D8E9";
    };
    "nix-public/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom";
      sha256 = "FDE386A7905173A1B103DE6AB820727584B50D0E32282E2797787C20A64FFA93";
    };
    "nix-public/org/hamcrest/hamcrest-parent/1.3/" = {
      url = "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-parent/1.3/";
      sha256 = "7099C54BF4F17660A105A68199213FFD80BCBBB1961BA78AD41E3CBFE3D65344";
    };
    "nix-public/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom";
      sha256 = "6D535F94EFB663BDB682C9F27A50335394688009642BA7A9677504BC1BE4129B";
    };
    "nix-public/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0-javadoc.jar";
      sha256 = "9175A09E404F75EC013219B54A51DF8788F890E0443BAE7A96FFC1AE74EF24F2";
    };
    "nix-public/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0-sources.jar";
      sha256 = "C0926003987A5C21108748FDA401023485085EAA9FE90A41A40BCF67596FFF34";
    };
    "nix-public/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0.jar";
      sha256 = "D9D5DFD1BC49A8158E6E0A90B2ED08FA602984D815C00AF16CEC53557E83EF8E";
    };
    "nix-public/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0.pom";
      sha256 = "49E2711154CE9BA76962E043F4F8A6D0B890CD9E2FC6D0E99C3A0E6AD6C1950E";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.0.4/scala-parser-combinators_2.12-1.0.4-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.0.4/scala-parser-combinators_2.12-1.0.4-javadoc.jar";
      sha256 = "228DA077BAEB60BB35E612780FB805126B0F88F9319AFDEA60E3BABEBC798BC2";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.0.4/scala-parser-combinators_2.12-1.0.4-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.0.4/scala-parser-combinators_2.12-1.0.4-sources.jar";
      sha256 = "CB4BA7B7E598530FAEC863E5069864A28268EE4C636B0C46443884DCC4E07AC6";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.0.4/scala-parser-combinators_2.12-1.0.4.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.0.4/scala-parser-combinators_2.12-1.0.4.jar";
      sha256 = "282C78D064D3E8F09B3663190D9494B85E0BB7D96B0DA05994FE994384D96111";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.0.4/scala-parser-combinators_2.12-1.0.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.0.4/scala-parser-combinators_2.12-1.0.4.pom";
      sha256 = "B512704E22EEF743D6288DED94943DFE78F9BB0636CCB5AC1919364BF0B4EF2A";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.5/scala-xml_2.12-1.0.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.5/scala-xml_2.12-1.0.5.jar";
      sha256 = "035015366F54F403D076D95F4529CE9EEAF544064DBC17C2D10E4F5908EF4256";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.5/scala-xml_2.12-1.0.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.5/scala-xml_2.12-1.0.5.pom";
      sha256 = "6509A7D180DB8AC5D33569FDB2AC79909B52CBFC4FE823E0629BDE0B51369BFE";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-javadoc.jar";
      sha256 = "FF42809FBF887885C957B3D368A909C6CCDDEA4C0485E4FE3A6465ED7747B636";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-sources.jar";
      sha256 = "A7E8AAC79394DF396AFDA98B35537791809D815CE15AB2224F7D31E50C753922";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar";
      sha256 = "7CC3B6CEB56E879CB977E8E043F4BFE2E062F78795EFD7EFA09F85003CB3230A";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.pom";
      sha256 = "A8FDB9C75E3333D442F2CBE283F1E0F8573FF33F87CFE6DC22D154ABD0D29A0B";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.5/scala-compiler-2.12.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.5/scala-compiler-2.12.5-javadoc.jar";
      sha256 = "FC8B711CF6EBAE8930B586911369DE8933AFB1ABA8652D75E87CAF614235768A";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.5/scala-compiler-2.12.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.5/scala-compiler-2.12.5-sources.jar";
      sha256 = "ABF4610BFF32478B164D33653AA9A253C1509D0CD9505010AB25DAA9F9D717F6";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.5/scala-compiler-2.12.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.5/scala-compiler-2.12.5.jar";
      sha256 = "A113394B6F857E69EF5D95B77114EC3F12CB0E14D9EDE32DE0BBC9C36D677455";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.5/scala-compiler-2.12.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.5/scala-compiler-2.12.5.pom";
      sha256 = "375324D0A18D3C11E8F2FAACFB193CDC454FAECC19882BAB41B14629432276C1";
    };
    "nix-public/org/scala-lang/scala-library/2.12.1/scala-library-2.12.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.1/scala-library-2.12.1.jar";
      sha256 = "9DAB78F3F205A038F48183B2391F8A593235F794D8129A479E06AF3E6BC50EF8";
    };
    "nix-public/org/scala-lang/scala-library/2.12.1/scala-library-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.1/scala-library-2.12.1.pom";
      sha256 = "E2C373E1C000D8431BD625729DB33DCE68B379D3537769D29E18514CB2B3050C";
    };
    "nix-public/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4-javadoc.jar";
      sha256 = "23443C33B32E3CC9FF6BABB69012E4CD0D4D68CB2AA6B19ADDE1FB274BD45F58";
    };
    "nix-public/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4-sources.jar";
      sha256 = "B9C34CF968A0E348ECEC32837797A794FFEADE2FE016323474FE756CB7D74042";
    };
    "nix-public/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4.jar";
      sha256 = "17824FCEE4D3F46CFAA4DA84EBAD4F58496426C2B9BC9E341F812AB23A667D5D";
    };
    "nix-public/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4.pom";
      sha256 = "63BDCD46CED3D72F03C38DFCDAF610BB94A286E317C072078D8E0B729B55A099";
    };
    "nix-public/org/scala-lang/scala-library/2.12.5/scala-library-2.12.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.5/scala-library-2.12.5-javadoc.jar";
      sha256 = "81EE9FCE5DB0E48FE2FCAA2431FCEC7A3E34E2AD96AA5D729E81399D3DD45AD9";
    };
    "nix-public/org/scala-lang/scala-library/2.12.5/scala-library-2.12.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.5/scala-library-2.12.5-sources.jar";
      sha256 = "0866105EC1FDFC0CA8C7EF04DE70BC1628E585D5496FA7B3FB7B2A9661119D30";
    };
    "nix-public/org/scala-lang/scala-library/2.12.5/scala-library-2.12.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.5/scala-library-2.12.5.jar";
      sha256 = "C2636320D6479C82F2DA6B8D76A820DE9345A61327E648D4298A0048154FB87C";
    };
    "nix-public/org/scala-lang/scala-library/2.12.5/scala-library-2.12.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.5/scala-library-2.12.5.pom";
      sha256 = "0C524D9C1E14F0C6AEB58A03FFC0F7D3428DA3E3BD6B727D2F80E52603438719";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.1/scala-reflect-2.12.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.1/scala-reflect-2.12.1.jar";
      sha256 = "D8A2B9D6D78C7457A40E394DC0C4FA6D6244ACF0D156BBBCB311A9D497B85EEC";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.1/scala-reflect-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.1/scala-reflect-2.12.1.pom";
      sha256 = "808B17C95D7E260A375615992CD1FCE7D759B6FDEF5E64D7B70E3942AE014261";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.5/scala-reflect-2.12.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.5/scala-reflect-2.12.5-javadoc.jar";
      sha256 = "AB9EF33B969369FAB20616EE72FDD97C716C99064B6D846CB950C6CA74D101E5";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.5/scala-reflect-2.12.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.5/scala-reflect-2.12.5-sources.jar";
      sha256 = "BFC0E84A8C33801A2210D330C31EB2DE230C64F71A9DFADF34D0097EF8987F68";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.5/scala-reflect-2.12.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.5/scala-reflect-2.12.5.jar";
      sha256 = "27036D7574AFFF72294F0E63D54AA13ACD8B16B525D51475691118B835E626E7";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.5/scala-reflect-2.12.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.5/scala-reflect-2.12.5.pom";
      sha256 = "489B4276EE17427BBE1356CA2C6F8411CFC63B4425581F37BD7D09F852839976";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.1.5/compiler-bridge_2.12-1.1.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.1.5/compiler-bridge_2.12-1.1.5-sources.jar";
      sha256 = "235D6D28E9FA5F2A7C1A48E21DDE5C85B93A94BD009ECBF95CF839D0F501404D";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.1.5/compiler-bridge_2.12-1.1.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.1.5/compiler-bridge_2.12-1.1.5.pom";
      sha256 = "A1C2D2DA03BE135913D73BDF28457E2C5BE6433DC88109F01193D8B0FECEA450";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.1.5/compiler-interface-1.1.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.1.5/compiler-interface-1.1.5-javadoc.jar";
      sha256 = "8E3243F8B04D3621DC2753EB3A24C2403C33F06D543B22DAF3367C88692C8FBD";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.1.5/compiler-interface-1.1.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.1.5/compiler-interface-1.1.5-sources.jar";
      sha256 = "9FE103830A26E876F3EB0E85D1B91876AF7881A0B958E87E78A48D1DE1EB67BD";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.1.5/compiler-interface-1.1.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.1.5/compiler-interface-1.1.5.jar";
      sha256 = "E3EE5ECA6CF7D5340FA8D95CF890B2CB4391E1FC3344BFADA72191DA05C19643";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.1.5/compiler-interface-1.1.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.1.5/compiler-interface-1.1.5.pom";
      sha256 = "9E43B91725CF5F19F3CCCEF9C86699D9728046C054613A164BC463BCDBFA5F4C";
    };
    "nix-public/org/scala-sbt/util-interface/1.1.3/util-interface-1.1.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.1.3/util-interface-1.1.3-javadoc.jar";
      sha256 = "D49E6F88991B4D4A4E920FDED02220B5A03D2A496512F0B5FB1F39EF39AE2C00";
    };
    "nix-public/org/scala-sbt/util-interface/1.1.3/util-interface-1.1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.1.3/util-interface-1.1.3-sources.jar";
      sha256 = "2E194C784C8C9DD3D34603A4378BFA7193708C1DECBA0DDB9AAFE5B1CECCB6AB";
    };
    "nix-public/org/scala-sbt/util-interface/1.1.3/util-interface-1.1.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.1.3/util-interface-1.1.3.jar";
      sha256 = "C671B55697207EB7AC680FEA390C249F383FDF2E445B3E98F8CAE4F6BC324860";
    };
    "nix-public/org/scala-sbt/util-interface/1.1.3/util-interface-1.1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.1.3/util-interface-1.1.3.pom";
      sha256 = "1D71466D429433C0D1D45C406018032AB2AFAA942FB26B16E40A057AED0A31F6";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.0.3/scalactic_2.12-3.0.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.0.3/scalactic_2.12-3.0.3.jar";
      sha256 = "245AD1BAAB6661AEE70C137C5E1625771C2624596B349B305801D94618673292";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.0.3/scalactic_2.12-3.0.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.0.3/scalactic_2.12-3.0.3.pom";
      sha256 = "0B33F9E2D47FA7F829E7E1646BD3EE3D4A4FF4E8A61775F345449E1D5757EB46";
    };
    "nix-public/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.jar";
      sha256 = "353F7C2BDDE22C4286EE6A3AE0E425A9463B102F4C4CF76055A24F4666996762";
    };
    "nix-public/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_2.12/3.0.3/scalatest_2.12-3.0.3.pom";
      sha256 = "BD17D616E1E6CA6DD9E5DF206B2BD43F435D72D4027ACF385C63CB85CEB7D4F3";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-javadoc.jar";
      sha256 = "8DC4B97B764D6C5B732479936C6CA28DFE9480C8A9B67E4B26CF95C8C64D77BD";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-sources.jar";
      sha256 = "C4BC93180A4F0ACEEC3B057A2514ABE04A79F06C174BBED910A2AFB227B79366";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar";
      sha256 = "18C4A0095D5C1DA6B817592E767BB23D29DD2F560AD74DF75FF3961DBDE25B79";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom";
      sha256 = "7CD9D7A0B5D93DFD461A148891B43509CF403A9C7F9FB49060D3554DF1C81E1E";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.jar";
      sha256 = "059A84383FAD78D85D9C3951BEBAFAB7200C704C411A9D25C913340C3877604A";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.pom";
      sha256 = "7A9E7276C1D353D2B2014BB4EE20446EF016A99E72D9B7B7AC3B380CBD0C3685";
    };
    "nix-public/org/slf4j/slf4j-parent/1.7.25/" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.25/";
      sha256 = "196657D089A56547578BC3BE1D1CADE6F6CC6EF50A8F7DC557FBD4E74820315A";
    };
    "nix-public/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom";
      sha256 = "18F5C52120DB036E88D6136F8839C832D074BDDA95C756C6F429249D2DB54AC6";
    };
    "nix-public/org/slf4j/slf4j-parent/1.7.6/" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.6/";
      sha256 = "8DBF41BBBF762C0880B75EE95B8145624807A6A842E53C053F90E61C6302C2D7";
    };
    "nix-public/org/slf4j/slf4j-parent/1.7.6/slf4j-parent-1.7.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.6/slf4j-parent-1.7.6.pom";
      sha256 = "69D805262EDE4EAC3C0F15825C8B1343A6F741AD96892C3C4F04F196D84FE206";
    };
    "nix-public/org/sonatype/oss/oss-parent/9/" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/";
      sha256 = "A1A235178FA1985CE3057440CAF2E309E2608BAF28D3441E04F4A0404B38E535";
    };
    "nix-public/org/sonatype/oss/oss-parent/9/oss-parent-9.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom";
      sha256 = "FB40265F982548212FF82E362E59732B2187EC6F0D80182885C14EF1F982827A";
    };
  };
}
